# Generated by Django 4.1.2 on 2022-12-16 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField()),
                ('desc', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_set', to='home.playlistnode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
