# Generated by Django 4.1.2 on 2022-12-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_playlistnode_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistnode',
            name='url',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
