# Generated by Django 4.1.2 on 2022-12-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_playlistnode_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistnode',
            name='slug',
            field=models.CharField(max_length=127, null=True, unique=True),
        ),
    ]
