# Generated by Django 4.1.2 on 2022-12-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_playlistnode_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistnode',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
