# Generated by Django 4.1.2 on 2022-12-16 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_playlistnode_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistnode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_set', to='home.playlistnode'),
        ),
    ]
