# Generated by Django 4.1.2 on 2022-12-16 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_playlistnode_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistnode',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_set', to='home.playlistnode'),
        ),
        migrations.AlterField(
            model_name='playlistnode',
            name='url',
            field=models.URLField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
