# Generated by Django 4.1.2 on 2022-12-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_playlistnode_parent_alter_playlistnode_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistnode',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
