# Generated by Django 4.1.2 on 2022-12-18 18:35

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_playlistnode_project_id_alter_playlistnode_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlistnode',
            old_name='desc',
            new_name='title',
        ),
        migrations.AddField(
            model_name='playlistnode',
            name='text',
            field=martor.models.MartorField(default=1),
            preserve_default=False,
        ),
    ]
