# Generated by Django 4.1.2 on 2022-12-18 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_desc_playlistnode_title_playlistnode_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistnode',
            name='post',
        ),
    ]
